workflows:
  android-release:
    name: PS Keyboard Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
      groups:
        - keystore_credentials # User credentials for release signing
      vars:
        PACKAGE_NAME: "com.ps.keyboard"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Run unit & widget tests
        script: |
          flutter test
      - name: Build Android APK
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - developer@pskeyboard.com
        notify:
          success: true
          failure: true
